on: push
name: IM Notification Demo
jobs:
  notification:
    name: IM Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Notify to IM
      uses: echoings/actions.notify@v0.1.0
      with:
        plat_type: 'Lark'
        notify_title: '项目更新'
        notify_message: '请点击下方链接查看详细'
      env:
        NOTIFY_WEBHOOK: ${{ secrets.NOTIFY_WEBHOOK }}
        NOTIFY_SIGNKEY: ${{ secrets.NOTIFY_SIGNKEY }}
        # for Lark use
        LARK_APP_ID: ${{ secrets.LARK_APP_ID }}
        LARK_APP_SECRECT: ${{ secrets.LARK_APP_SECRECT }}
